export const register = {
  title: 'Crear cuenta',
  subtitle: 'Únete a nuestra plataforma',
  step1Subtitle: 'Información de la empresa',
  step1: 'Paso 1: Detalles de la empresa',
  step2: 'Paso 2: Información personal',
  step1Title: 'Información de la empresa',
  step2Title: 'Información personal',
  step2Subtitle: 'Ingresa tu información personal',
  submit: 'Crear cuenta',
  creating: 'Creando cuenta...',
  validating: 'Validando...',
  hasAccount: '¿Ya tienes una cuenta?',
  alreadyHaveAccount: '¿Ya tienes una cuenta?',
  continue: 'Continuar',
  signIn: 'Iniciar sesión',
  success: 'Cuenta creada con éxito',
  error: 'Error al crear la cuenta',
  nextStep: 'Siguiente',
  previousStep: 'Anterior',
  back: 'Atrás',
  acceptTerms: 'Acepto los',
  and: 'y',
  termsLink: 'Términos de servicio',
  privacyLink: 'Política de privacidad',
  createAccount: 'Crear cuenta'
}
