export const register = {
  title: 'Create account',
  subtitle: 'Join our platform',
  step1Subtitle: 'Company information',
  step1: 'Step 1: Company Details',
  step2: 'Step 2: Personal Information',
  step1Title: 'Company information',
  step2Title: 'Personal information',
  step2Subtitle: 'Enter your personal information',
  submit: 'Create account',
  creating: 'Creating account...',
  validating: 'Validating...',
  hasAccount: 'Already have an account?',
  alreadyHaveAccount: 'Already have an account?',
  continue: 'Continue',
  signIn: 'Sign in',
  success: 'Account created successfully',
  error: 'Error creating account',
  nextStep: 'Next',
  previousStep: 'Previous',
  back: 'Back',
  acceptTerms: 'I accept the',
  and: 'and',
  termsLink: 'Terms of Service',
  privacyLink: 'Privacy Policy',
  createAccount: 'Create Account'
}
