name: CI/CD
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest' # o fija una versión como '1.1.8'

      - name: Install dependencies
        run: bun install

      # 1) Type check
      - name: Type check
        run: bun run type-check

      # 2) Lint check
      - name: Lint check
        run: bun run lint

      # 3) Test check
      - name: Run tests
        run: bun run test-report

      - name: Upload coverage to comment
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: './coverage/coverage-summary.json'
          json-final-path: './coverage/coverage-final.json'

      # Add your deployment steps here
      - name: Deploy
        run: bun run build
